Extensive changes to execute in the AXLE machine at BSC

diff --git a/tpch_prepare b/tpch_prepare
--- a/tpch_prepare
+++ b/tpch_prepare
@@ -8,23 +8,19 @@ BASEDIR=$(dirname "$0")
 BASEDIR=$(cd "$BASEDIR"; pwd)
 . "$BASEDIR/pgtpch_defaults"
 
-#
 # Initialize DB if $PGDATADIR does not exist
-#
 if ! [ -d "$PGDATADIR" ]; then
-  mkdir -p "$PGDATADIR"
-  initdb -D "$PGDATADIR" --encoding=UTF-8 --lc-ctype=en_US.UTF-8 --lc-collate=en_US.UTF-8
+  sudo -u $PGUSER mkdir -p "$PGDATADIR"
+  sudo -u $PGUSER initdb -D "$PGDATADIR" --encoding=UTF-8 --locale=C
   CREATE_NEW_DB=true
 else
   CREATE_NEW_DB=false
 fi
 
-#
 # Start a new instance of Postgres
-#
-postgres -D "$PGDATADIR" -p $PGPORT &
+sudo -u $PGUSER postgres -D "$PGDATADIR" -p $PGPORT &
 PGPID=$!
-while ! pg_ctl status -D $PGDATADIR | grep "server is running" -q; do
+while ! sudo -u $PGUSER pg_ctl status -D $PGDATADIR | grep "server is running" -q; do
   echo "Waiting for the Postgres server to start"
   sleep 1
 done
@@ -33,11 +29,11 @@ done
 sleep 2
 
 if $CREATE_NEW_DB; then
-  createdb -p $PGPORT $USER --encoding=UTF-8 --lc-ctype=en_US.UTF-8 --lc-collate=en_US.UTF-8
+  sudo -u $PGUSER createdb -h /tmp -p $PGPORT $PGUSER --encoding=UTF-8 --locale=C
 fi
 
-WAL_LEVEL_MINIMAL=`psql -p $PGPORT -c 'show wal_level' -t | grep minimal | wc -l`
-DEBUG_ASSERTIONS=`psql -p $PGPORT -c 'show debug_assertions' -t | grep on | wc -l`
+WAL_LEVEL_MINIMAL=`sudo -u $PGUSER psql -h /tmp -p $PGPORT -c 'show wal_level' -t | grep minimal | wc -l`
+DEBUG_ASSERTIONS=`sudo -u $PGUSER psql -h /tmp -p $PGPORT -c 'show debug_assertions' -t | grep on | wc -l`
 
 # disable resolving of *.tbl to '*.tbl' in case there are no matching files
 shopt -s nullglob
@@ -69,20 +65,20 @@ function die()
 }
 
 # Remind me of my current settings
-psql -p $PGPORT -c "select name, current_setting(name) from pg_settings where name
+sudo -u $PGUSER psql -h /tmp -p $PGPORT -c "select name, current_setting(name) from pg_settings where name
 in('debug_assertions', 'wal_level', 'checkpoint_segments', 'shared_buffers', 'wal_buffers',
 'fsync', 'maintenance_work_mem', 'checkpoint_completion_target',
 'max_connections');"
 
 if [ $WAL_LEVEL_MINIMAL != 1 ] ;
 then
-	echo "Warning: Postgres wal_level is not set to minimal; 'Elide WAL traffic' optimization cannot be used">&2
+    echo "Warning: Postgres wal_level is not set to minimal; 'Elide WAL traffic' optimization cannot be used">&2
 fi
 
 if [ $DEBUG_ASSERTIONS = 1 ] ;
 then
-	echo "Error: debug_assertions are enabled">&2
-	exit -1
+    echo "Error: debug_assertions are enabled">&2
+    exit -1
 fi
 
 cd "$BASEDIR/dbgen"
@@ -91,36 +87,51 @@ then
   make -j $CORES
 fi
 
-mkdir -p "$TPCHTMP" || die "Failed to create temporary directory: '$TPCHTMP'"
+sudo -u $PGUSER mkdir -p "$TPCHTMP" || die "Failed to create temporary directory: '$TPCHTMP'"
 
 if $REMAKE_DATA
 then
   cd "$TPCHTMP"
-  cp "$BASEDIR/dbgen/dists.dss" .
+  sudo -u $PGUSER cp "$BASEDIR/dbgen/dists.dss" .
   # Run dbgen with "force", to overwrite existing files
-  "$BASEDIR/dbgen/dbgen" -s $SCALE -f -v
+  sudo -u $PGUSER "$BASEDIR/dbgen/dbgen" -s $SCALE -f -v
 fi
+
+data_loading_configuration="
+checkpoint_segments = 300
+checkpoint_timeout = 3600s
+checkpoint_completion_target = 0.9
+shared_buffers = 32GB
+maintenance_work_mem = 1GB
+"
 
 if $POPULATE_DB
 then
-  echo "DROP DATABASE IF EXISTS $DB_NAME" | psql -p $PGPORT
+  echo "DROP DATABASE IF EXISTS $DB_NAME" | sudo -u $PGUSER psql -h /tmp -p $PGPORT
   # Make sure we're all on the same page wrt encoding, collations, etc.
-  createdb -p $PGPORT $DB_NAME --encoding=UTF-8 --lc-ctype=en_US.UTF-8 --lc-collate=en_US.UTF-8
+  sudo -u $PGUSER createdb -h /tmp -p $PGPORT $DB_NAME --encoding=UTF-8 --locale=C
   if [ $? != 0 ]; then
     # Did you forget to disconnect from the database before dropping?
-	echo "Error: Can't proceed without database"
-	exit -1
+    echo "Error: Can't proceed without database"
+    exit -1
   fi
+
   TIME=`date`
-  psql -p $PGPORT -d $DB_NAME -c "comment on database $DB_NAME is 'TPC-H data, created at $TIME'"
-  psql -p $PGPORT -d $DB_NAME < "$BASEDIR/dbgen/dss.ddl"
+  sudo -u $PGUSER psql -h /tmp -p $PGPORT -d $DB_NAME -c "comment on database $DB_NAME is 'TPC-H data, created at $TIME'"
+  sudo -u $PGUSER psql -h /tmp -p $PGPORT -d $DB_NAME < "$BASEDIR/dbgen/dss.ddl"
+
+  # Configuration parameters for efficient data loading
+  #sudo -u $PGUSER chmod 666 $PGDATADIR/postgresql.conf
+  echo "$data_loading_configuration" | sudo -u $PGUSER tee -a $PGDATADIR/postgresql.conf
+  sudo -u $PGUSER pg_ctl reload -D $PGDATADIR
+
   cd "$TPCHTMP"
   for f in *.tbl; do
-	bf="$(basename $f .tbl)"
-	# We truncate the empty table in the sames transaction to enable Postgres to
-	# safely skip WAL-logging. See
-	# http://www.postgresql.org/docs/current/static/populate.html#POPULATE-PITR
-    echo "truncate $bf; COPY $bf FROM '$(pwd)/$f' WITH DELIMITER AS '|'" | psql -p $PGPORT -d $DB_NAME &
+    bf="$(basename $f .tbl)"
+    # We truncate the empty table in the sames transaction to enable Postgres to
+    # safely skip WAL-logging. See
+    # http://www.postgresql.org/docs/current/static/populate.html#POPULATE-PITR
+    echo "truncate $bf; COPY $bf FROM '$(pwd)/$f' WITH DELIMITER AS '|'" | sudo -u $PGUSER psql -h /tmp -p $PGPORT -d $DB_NAME &
   done
   # TODO: It would be nice if there was a way to limit the number of
   # concurrently executing jobs to $CORES. It is surprisingly easy to make COPY
@@ -132,14 +143,14 @@ then
 fi
 
 cd "$BASEDIR"
-rm -rf "$TPCHTMP"
+sudo -u $PGUSER rm -rf "$TPCHTMP"
 
 # Since wal_level is hopefully set to 'minimal', it ought to be possible to skip
 # WAL logging these create index operations, too.
 if $CREATE_ALL_INDEXES
 then
 echo "Creating 'All' indexes..."
-psql -p $PGPORT -d $DB_NAME -c "CREATE INDEX i_l_shipdate ON lineitem (l_shipdate);
+sudo -u $PGUSER  psql -h /tmp -p $PGPORT -d $DB_NAME -c "CREATE INDEX i_l_shipdate ON lineitem (l_shipdate);
 CREATE INDEX i_l_suppkey_partkey ON lineitem (l_partkey, l_suppkey);
 CREATE INDEX i_l_partkey ON lineitem (l_partkey);
 CREATE INDEX i_l_suppkey ON lineitem (l_suppkey);
@@ -153,12 +164,19 @@ CREATE INDEX i_s_nationkey ON supplier (s_nationkey);
 CREATE INDEX i_ps_partkey ON partsupp (ps_partkey);
 CREATE INDEX i_ps_suppkey ON partsupp (ps_suppkey);
 CREATE INDEX i_n_regionkey ON nation (n_regionkey);
-CREATE INDEX i_l_commitdate ON lineitem (l_commitdate);"
+CREATE INDEX i_l_commitdate ON lineitem (l_commitdate);
+CREATE INDEX i_n_nationkey ON nation (n_nationkey);
+CREATE INDEX i_r_regionkey ON region (r_regionkey);
+CREATE INDEX i_p_partkey ON part (p_partkey);
+CREATE INDEX i_s_suppkey ON supplier (s_suppkey);
+CREATE INDEX i_c_custkey ON customer (c_custkey);
+CREATE INDEX i_o_orderkey ON orders (o_orderkey);"
 fi
+
 if $CREATE_MIN_INDEXES
 then
 echo "Creating 'Min' indexes..."
-psql -p $PGPORT -d $DB_NAME -c "CREATE INDEX n_nationkey_idx on nation (n_nationkey);
+sudo -u $PGUSER psql -h /tmp -p $PGPORT -d $DB_NAME -c "CREATE INDEX n_nationkey_idx on nation (n_nationkey);
 CREATE INDEX r_regionkey_idx on region (r_regionkey);
 CREATE INDEX p_partkey_idx on part (p_partkey);
 CREATE INDEX s_suppkey_idx on supplier (s_suppkey);
@@ -169,14 +187,28 @@ CREATE INDEX l_orderkey_idx on lineitem (l_orderkey);
 CREATE INDEX l_partkey_idx on lineitem (l_partkey);"
 fi
 
+# Configuration for query execution
+query_configuration="
+checkpoint_timeout = 600s
+work_mem = 12GB                      #2 to 16GB
+effective_cache_size = 192GB        #3/4 of total RAM (192GB)
+default_statistics_target = 5000    #requires analyze to take effect
+maintenance_work_mem = 32MB
+"
+echo "$query_configuration" | sudo -u $PGUSER tee -a $PGDATADIR/postgresql.conf
+sudo -u $PGUSER pg_ctl reload -D $PGDATADIR
+
+# Disable transparent huge pages
+echo never | sudo tee /sys/kernel/mm/transparent_hugepage/defrag
+
 # Always analyze after bulk-loading; when hacking Postgres, typically Postgres
 # is run with autovacuum turned off.
-echo "Running analyze..."
-psql -p $PGPORT -d $DB_NAME -c "analyze"
+echo "Running vacuum freeze analyze..."
+sudo -u $PGUSER psql -h /tmp -p $PGPORT -d $DB_NAME -c "vacuum freeze"
+sudo -u $PGUSER psql -h /tmp -p $PGPORT -d $DB_NAME -c "analyze"
 # Checkpoint, so we have a "clean slate". Just in-case.
 echo "Checkpointing..."
-psql -p $PGPORT -d $DB_NAME -c "checkpoint"
-
+sudo -u $PGUSER psql -h /tmp -p $PGPORT -d $DB_NAME -c "checkpoint"
 
 cd "$BASEDIR/dbgen"
 for i in $(seq 1 22);
@@ -184,10 +216,7 @@ do
   ii=$(printf "%02d" $i)
   mkdir -p "../queries"
   DSS_QUERY=queries ./qgen $i >../queries/q$ii.sql
-  # create a file with all the queries in sequence
-  cat ../queries/q$ii.sql >> ../queries/qall.sql
+  sed 's/^select/explain select/' ../queries/q$ii.sql > ../queries/q$ii.explain.sql
 done
-
-pgtune -T DW -i $PGDATADIR/postgresql.conf -o $PGDATADIR/postgresql.conf
 
 printf 'Elapsed time: %s\n' $(timer $t)
